const { chromium } = require('C:/Users/xiexi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless: true, executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
  const page = await browser.newPage({viewport:{width:1600,height:1000}, deviceScaleFactor:1});
  const errors = [];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4173');
  await page.screenshot({path:'preview-desktop.png', fullPage:true});
  assert.equal(await page.locator('.node').count(),6);
  await page.locator('[data-asset="city"]').dragTo(page.locator('#node-video'));
  assert.match(await page.locator('#inspectorDrop').innerText(),/雨夜/);
  await page.locator('#promptField').fill('缓慢向前推进，雨滴落在街道上。');
  await page.locator('#durationField').selectOption('10 秒');
  assert.match(await page.locator('#node-video').innerText(),/10 秒/);
  await page.locator('#zoomIn').click();
  await page.locator('#fitCanvas').click();
  const header=page.locator('#node-image .node-header');
  const before=await page.locator('#node-image').boundingBox();
  const hb=await header.boundingBox();
  await page.mouse.move(hb.x+60,hb.y+10); await page.mouse.down();
  await page.mouse.move(hb.x+90,hb.y+30,{steps:5}); await page.mouse.up();
  const after=await page.locator('#node-image').boundingBox();
  assert.ok(after.x>before.x+20,'node drag updates position');
  await page.locator('[data-view="story"]').click();
  assert.equal(await page.locator('.story-card').count(),6);
  await page.locator('.story-card').first().click();
  assert.ok(await page.locator('#previewDialog').isVisible());
  await page.locator('#nextShot').click();
  assert.match(await page.locator('#previewTitle').innerText(),/一封旧信/);
  await page.locator('#closePreview').click();
  await page.locator('[data-view="canvas"]').click();
  await page.locator('#runAll').click();
  await page.waitForFunction(()=>document.querySelector('#runAll').disabled===false);
  assert.equal(await page.locator('.node-status').filter({hasText:'演示完成'}).count(),6);
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#exportBtn').click();
  const download=await downloadPromise;
  assert.match(download.suggestedFilename(),/工作流方案/);
  await page.reload();
  await page.screenshot({path:'preview-desktop.png',fullPage:true});
  await page.setViewportSize({width:1280,height:800});
  await page.waitForTimeout(250);
  await page.screenshot({path:'preview-laptop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(250);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#inspectorToggle').click();
  assert.ok(await page.locator('#inspector').isVisible());
  await page.locator('#inspectorToggle').click();
  await page.screenshot({path:'preview-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS: drag reference, edit prompt, parameter update, node drag, zoom, storyboard, preview, simulated run, JSON download, mobile layout; no page errors.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
